services:

  # ────────────────────────────────
  # Production service (runs in Swarm)
  # ────────────────────────────────
  ethelapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ethel/ethelapp:latest
    networks:
      - ethel_net
    ports:
      - "3000:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # ────────────────────────────────
  # Dev‐only service (use Node container, hot-reload)
  # ────────────────────────────────
  ethelapp-dev:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host"
    volumes:
      - .:/app:delegated          # mount your source
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"  # if you need file-watch in some setups
    profiles:
      - dev                        # only starts when you pass --profile dev

networks:
  ethel_net:
    external: true

volumes:
  node_modules:

