services:
  ethelapp:
    image: ethel/ethelapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    # map host 8443 → container 443
    ports:
      - "8443:443"
    # mount your live certs and override default conf
    volumes:
      - /etc/letsencrypt/fullchain.pem:/run/certs/fullchain.pem:ro
      - /etc/letsencrypt/privkey.pem:/run/certs/privkey.pem:ro
      - ./nginx.ssl.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ethel_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  ethel_net:
    external: true

