services:
  ethelapp:
    image: ethel/ethelapp:latest
    ports:
      - "3000:80"
    networks:
      - ethel_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  ethel_net:
    external: true

