#!/bin/bash

# Check if exactly one argument is provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 [up|down]"
    exit 1
fi

# Perform action based on the argument
case $1 in
    up)
        echo "Deploying ethelapp prod stack..."
        docker stack deploy   --resolve-image never   -c docker-compose.yml   ethelapp
        ;;
    down)
        echo "Removing ethelapp dev stack..."
        docker stack rm ethelapp
        ;;
    *)
        echo "Invalid argument: $1"
        echo "Usage: $0 [up|down]"
        exit 2
        ;;
esac
